### ISSUE TITLE
No notifications (running without a SIM card)

### ISSUE THREAD

**Issue by nonprofitable** [guardianproject/haven#141]
First try setting up Haven on an old Motorola G (third generation), Android 6.01, security patch level April '17.

Did the initial config. Set it up to send SMS / Signal notifications. Motion detection seems to work flawlessly, and it records a stream of events, but doesn't send notifications. 

Attempted to configure Signal. There's an unclear setting to register a new number with Signal (not sure what this is for) that has a number pre-filled, and a warning not to register my primary Signal number. I attempted to register a Google Voice number here as a workaround, but Google Voice never receives the confirmation SMS. 

Is it not possible to receive notifications without an active SIM card in the phone? Meaning that older phones won't work without active SIMs, even on wifi networks?

**Comment by leonardoporpora** [comment]
Once you activate signal you do not need anymore the SIM in the Haven phone. For example I never put the SIM inside the Haven phone. During the registration I used my work phone I checked for the verification code and I registered Signal account on the Haven phone. 
So now I receive messages through Signal that is connected obviously to the WiFi (because I haven’t got a SIM into that phone)

**Comment by n8fr8** [comment]
We will also add a feature to receive the Signal verification code via a voice call, so you can use a non-mobile phone as the number.

**Comment by leonardoporpora** [comment]
Cool 😎

**Comment by n8fr8** [comment]
Voice call support is now in, so any phone you can receive a call at can be used as your Signal "local" or sending number.

That said, the whole Signal setup process is very confusing, and something we are still working on overhauling.
