### ISSUE TITLE
Can i ask a question about compiler?

### ISSUE THREAD

**Issue by DioBrandoLong** [guardianproject/haven#142]
i was using android studio but i can't direct open the project and running.
so  what kind of compiler i should have so that i can direct running this project?
please

**Comment by fat-tire** [comment]
If you are using the stable [Android Studio 3.0.1](https://developer.android.com/studio/index.html) or the [Canary 3.1 version](https://developer.android.com/studio/preview/index.html), it should have everything you need included.  You _used_ to have to download the SDK separately and point to it from within AS, but I think it's all bundled together now.

You should be able to git clone the repository to a spot on your computer.  On Linux it might look like:
```
$ mkdir ~/workspace
$ cd ~/workspace
$ git clone https://github.com/guardianproject/haven.git
```
Then in Android Studio, you can do:

**File**->**Open...**

The latest Haven source code should be downloaded.  Then select the directory `/home/diobrandolong/workspace/haven`

Put your username where **diobrandolong** is.  And the project should load up and you hit the green arrow to start building it :)

Something like that anyway.  This is assuming you don't have to load pieces any more like you used to.  If you are missing stuff, you can use the Sdk Manager to auto download it.  See the icon that looks like this:

![image](https://user-images.githubusercontent.com/528174/34404797-980b2706-eb64-11e7-9544-8293ac40608f.png)

**Comment by DioBrandoLong** [comment]
Great it's work! before i clone this project my androud studio version was 2.3.3.   Tank you guy's!

**Comment by mig5** [comment]
I'm trying to compile in Android Studio 3.1 too and I am getting an error on 401 Unauthorized for https://jitpack.io/com/github/derlio/waveform/library/1.0.3/library-1.0.3.pom :( this prevents me from running a virtual device or making the project in general

Any ideas? Surely must be a new/recent problem as it's a total blocker..

**Comment by fat-tire** [comment]
Hmm.  That url does require authentication, but the only place I'm seeing a reference to jitpack is [here](https://github.com/guardianproject/haven/blob/master/build.gradle#L32) which I don't think should cause that issue.   I don't see any changes in the [derlio](https://github.com/derlio/audio-waveform) library. I just built w/3.1 canary 6 (I jut updated it last night from 3.0.1)

Have you fully cleared the project and tried rebuilding?  And maybe even **File**->**Invalidate Caches/Restart** ?  What happens if you `git revert 1ebeba0c9ffcab0eb7830541b008227354042460` (that is, [this commit](https://github.com/guardianproject/haven/commit/1ebeba0c9ffcab0eb7830541b008227354042460))?
 
I did notice a similar issue [here](https://github.com/jitpack/jitpack.io/issues/1381) fwiw.

**Comment by mig5** [comment]
Cleaning/Rebuilding the project, as well as running the project after Invalidate, throws the same error.

Get an 'addinfo_cache failed for path...' when trying to revert, probably because so much has changed in the filesystem since. But it's surprising that no-one else has come up against this.

Thanks for the tips, I'll continue to debug..

**Comment by mig5** [comment]
@fat-tire can I ask, which SDK are you using in Android Studio?

**Comment by mig5** [comment]
Huh - well, I 'resolved' my issue by commenting out this line from build.gradle

```
maven { url 'https://jitpack.io' }
```

And instead adding:

```
maven { url 'https://maven.google.com' }
```

After this, a new Sync fetched the derlio waveform library from maven.google.com instead.

Now I have new errors about Failing to resolve com.github.com.guardianproject:signal-cli-android:-SNAPSHOT and com.github.api-devs:appintro:v4.2.2. On to the next piece of the puzzle (the project could really do with a BUILD.md that contains explicit steps to solve all these hidden gotchas, something for another day :) )

**Comment by mig5** [comment]
Possibly fixed by changing

```
compile 'com.github.derlio.waveform:library:1.0.3@aar'
```

To

```
compile 'com.github.derlio:audio-waveform:v1.0.1'
```

Per the instructions at https://jitpack.io/#derlio/audio-waveform

Still makes no sense though..
