### ISSUE TITLE
Register/Verify next to "Activate Signal" give no user feedback

### ISSUE THREAD

**Issue by Austin-Williams** [guardianproject/haven#202]
In "Settings" when the user is trying to activate Signal and trying to "REGISTER" of "VERIFY" a number, the user is given no feedback as to whether or not the verification was a success or failure.

To be specific, when I enter a phone number under "REGISTER", I receive a "Your Signal verification code: xxx-xxx" message via SMS at the number I enter.

However, when I click "VERIFY", enter that verification code, and click "verify", I get no feedback as to whether or not the verification was successful.

Testing via "SEND TEST MESSAGE" has never resulted in me receiving any message at the (known-good) signal number I enter.

**Comment by lukeswitz** [comment]
Try this workaround, the SQL database sometimes needs to be renamed. Or if you're not a developer, give this a shot, it worked on several devices that had been overwritten with new versions 

with existing Signal integration:

1.  Uninstall 
2.  Install latest F-droid build
3.  Don't enter any number in the setup
4.  Under settings, add your number to receive SMS/Signal
5.  Press 'Save', closing settings then reopen
6.  Enter the burner signal number
7.  Press verify and you will get a notification through your burner number with the activation code.
7.  Enter code and press 'Save' 
8. If test messages to the saved number work, Signal is linked to Haven and you're all good.


I hope that helps you out, otherwise you may have turned off notifications needed for the verification code to appear.

**Comment by Austin-Williams** [comment]
lukeswitz, that worked for me, thank you! Signal notifications are working great.

**Comment by n8fr8** [comment]
Still, we need a major overhaul to the user experience for setting this up... thanks for persevering for now!
