### ISSUE TITLE
Implement in-app video playback

### ISSUE THREAD

**Issue by n8fr8** [guardianproject/haven#246]
We shouldn't rely on the platform video player.

**Comment by lukeswitz** [comment]
Did you get vid capture working? On Nexus 4 the Camera fails with code -38 on begin capture and no events are recorded, video or otherwise. 

I believe that means a process somewhere is using the mic or the encoder settings don’t support the device. 
 
The ‘ImageCodec” drop in fix may be the issue, as it will only fix upside down images using a method not suited to the native api methods that are bound. 

That said, good idea to not give the media player a look at the stored data. Cheers

**Comment by n8fr8** [comment]
Should be fixed in 0.2.0 alpha 2
