### ISSUE TITLE
Crash - "MonitorActivity has Leaked ServiceConnection sensors" - Jelly Bean 4.1.2

### ISSUE THREAD

**Issue by Forgen** [guardianproject/haven#258]
An interesting crash. I think the app partially kept running in the background after this crash?  
```
android.app.ServiceConnectionLeaked: Activity org.havenapp.main.MonitorActivity has leaked ServiceConnection org.havenapp.main.sensors.motion.Preview$1@2cf2e148 that was originally bound here
                      at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:965)
   
```         

Crash using Haven V 0.1.0-beta-12 (112)  

Logcat excerpt:
[Haven_Service-Leak_Crash-2018-02-18.txt](https://github.com/guardianproject/haven/files/1735498/Haven_Service-Leak_Crash-2018-02-18.txt)

_Hardware Info:_
Phone: Proprietary, Unreleased Android Phone 
Android Version: 4.1.2 
RAM: 635 MB (as reported by Jelly Bean Settings -> Apps -> Running)

**Comment by lukeswitz** [comment]
Confirmed here as well, had to remove code that keeps the monitor bound improperly. Haven runs until you restart the native camera.
 
Devices tested: Nexus 4 on 5.1 & Pixel 2

Outcome: Bind handler errors, overheating on both.

Causes: 
* Switching the activity stack with the camera active. 
* Using settings from the preview screen to adjust sensitivity of camera. 
* Hiding the app while timer counts
* Resuming app from active state
* Attempt to view logs (button not handled properly) 

Big bug here caused by not using Camera2 API out of the gate. The imagecodec class comes into play for older devices, performing a second operation on each frame to ensure orientation and basically melting cpu’s if left running.

I made some adjustments so the Preview is only updated when bound correctly and memory use leveled out. However, the app crashes all over after that: it relies on heavy image processing alongside standard use.  

These are the pitfalls of using sample code or in this case an old app along with its dependencies. Starting fresh with camera surfaces wouldn’t be hard and would also allow multiple camera streaming and more feature implementation without as many bugs. 

The design audit is stunning and would actually solve a lot of the bugs caused by using a separate view for Settings without any code changes. 

An app with this potential deserves stability, and we simply won’t find that in 3rd party libraries. Supporting old and new is a challenge but nothing more, we’ve got this.
