### ISSUE TITLE
Signal registration fails in 0.2.0-alpha2

### ISSUE THREAD

**Issue by micahflee** [guardianproject/haven#315]
I have a Nexus 6P running the stock rom, and I installed `Haven-0.2.0-alpha-2-release.apk`. When I try registering a phone number with Signal, it fails, and the phone number never receives an SMS message. Here is the error (with the actual phone number redacted to `+1xxxxxxxxxx`):

```
07-14 19:11:38.082 12488 12536 W System.err: Failed to send (some) messages:
07-14 19:11:38.082 12488 12536 W System.err: Network failure for "+1xxxxxxxxxx": org.whispersystems.signalservice.api.push.exceptions.PushNetworkException: javax.net.ssl.SSLPeerUnverifiedException: Hostname textsecure-service.whispersystems.org not verified:
07-14 19:11:38.082 12488 12536 W System.err:     certificate: sha256/HM+ifSiHwpnXD9+puSNkx6xEtwuT5qtfJQNRH+NdoBc=
07-14 19:11:38.082 12488 12536 W System.err:     DN: CN=textsecure-service.whispersystems.org,OU=Open Whisper Systems,O=Open Whisper Systems,ST=California,C=US
07-14 19:11:38.082 12488 12536 W System.err:     subjectAltNames: []
```

When I run 0.1.0-RC-1, it works fine to register a phone number with Signal.

**Comment by lukeswitz** [comment]
Thank you for the logs, it’s a headache this bug. For now please use the first dev release. The media playback library is conflicting with Signal. 

Picasso: let’s fix integration or lose it. It’s wrecking this app.

A few other dependencies are not compatible however are included in that release. The haven signal-cli branch needs an update as well. @n8fr8, could it be using v4 instead of v13? 

Looking now, it crashes when I try and do anything after cam calibration. If I manually set the camera facing in settings to back and then open it no crash, but no camera. 

Hope that is of help. No use adding more features at this juncture until important issues are ironed out. I’ll dig in on my breaks and try to solve this.

**Comment by n8fr8** [comment]
Yeah, the goal is just improved performance and stability right now. I will update signal-cli as a start.

**Comment by n8fr8** [comment]
(Also I think this is just a case of two libraries competing for usage of HTTPS/TLS stack, and overwriting things like hostname verifies and Root CA stores)

**Comment by n8fr8** [comment]
Alright, just pushed more commits to my PR here #314 

- removed Picasso and used Fresco instead (since we already have that for the full image viewer)... that was super easy!
- updated signal-cli-android to 0.6.0: https://github.com/guardianproject/signal-cli-android/releases/tag/v0.6.0-android-beta-1
- made some other small changes to camera init/update behavior

**Comment by n8fr8** [comment]
Oh, and also tested Signal registration, and it seemed to work just fine.

**Comment by n8fr8** [comment]
New alpha build is up: https://github.com/guardianproject/haven/releases/tag/0.2.0-alpha-3

**Comment by n8fr8** [comment]
@micahflee reports the fix was good!
