### ISSUE TITLE
Heartbeat notification

### ISSUE THREAD

**Issue by micahflee** [guardianproject/haven#54]
Kind of related to #50 and #52, it would be cool if you could configure a heartbeat notification. So once an hour (or whatever interval you configure) you get a notification informing you that Haven is still activated.

**Comment by dad4x** [comment]
Do you think it's more useful to have the recpient get positive hb's, or more useful to get notified if there is a disruption?  I would also think think a higher hb rate is called for; typically in systems that do heartbeats, we wait for 2 or three missed ones before declaring a dead/sick sender.  (I'm more used to  heartbeats in the sub-second range, though)

**Comment by joncamfield** [comment]
I may simply have horrible luck with all things Android, but I'd be much more interested in a positive hb to keep me informed if something outside of the app's ability to notify me has happened (crashes, battery died, network is blocked, a very evil maid with a ball-peen hammer...).

This could be partially achieved by the concerned user poking at the onion service as well.

**Comment by secure-a-tea** [comment]
The key part of any alarm system is the signalling. The flashing lights and sirens are not as useful as you'd expect!

Good alarms nowadays use dedicated lines with a heartbeat signal to prevent cutting the wires. (guess how good the crypto is protecting the signal? almost certainly awful!)

In this case, jamming GSM and Wifi is a solved problem -- it's very easy for an attacker to wholly defeat Haven using off-the-shelf technology as it is currently designed.

The heartbeat signal needs to occur often enough to provide usable confirmation of an attack across a variety of scenarios: a heartbeat once an hour is not enough to provide security if you leave a room unattended for half an hour.

**Comment by n8fr8** [comment]
I wouldnt mind a 💓❤️ heart emoji every five minutes, sent via Signal. I could even mute notifications, and check it at my leisure. Definitely something we can make configurable. 

Even if the wifi or gsm is jammed, Signal will continue to capture the evidence locally. If the intruder also locates and steals the device, well that is plenty of evidence unto itself.

**Comment by secure-a-tea** [comment]
> Even if the wifi or gsm is jammed, Signal will continue to capture the evidence locally. If the intruder also locates and steals the device, well that is plenty of evidence unto itself.

As soon as the intruder enters the space, we can assume they have full access to the device and can alter or delete evidence at will. This is an Android burner with n-million vulnerabilities, not a hardware security module.

For Haven to successfully perform its function against nation-state adversaries depends on the VERY narrow window of time between the alarm being triggered and the intruder being able to alter the device.

If the intruder is also jamming Wi-Fi or GSM, then that window of time is gone -- the device can't call out, the intruder roots it and silently deletes evidence of the alarm going off (or makes it look like Haven failed due to an innocuous problem like the user having forgotten to turn it on)... game over!

How does this sort of attack work in practice?

Here's an example from New York in the 1970s... you'll see why it's relevant in a second.

There was a jeweler who had been burglarised several times, and he had gotten to be rather paranoid. Somehow the burglars always got away, despite the fact that he had the best security money could buy!

 So this time he had TWO separate alarm companies wire up his shop... neither alarm company knew much, if anything about the other's system... and the jeweler made sure the installers did not interact or talk to each other.

Then (once the alarm companies were done) he had a friend (an amateur radio operator) hide a simple radio transmitter in the attic of his shop... if EITHER alarm was triggered, it would send a signal across the street, where a tape recorder would turn on and dial the police.

A few months later, things went the way they usually did. A crew of burglars opened up a manhole down the street and neatly bypassed BOTH of the signalling wires to the jeweler's shop alarm systems.

The burglars proceeded to break into the shop, ignoring the wailing alarm siren... they knew nobody in the neighborhood would do anything, alarms went off all the time! By the time anyone got annoyed enough to phone the cops, the burglars would be long gone.

Except ... the burglary crew had got their information from the alarm company installers (they were all corrupt)... and didn't know about the "backup" radio. The cops showed up and arrested everyone, much to their surprise!

**Comment by lukeswitz** [comment]
#270 resolves, mark to close.
